[workspace]
resolver = "3"
members = [
    "crates/io",
    "crates/core",
    "crates/native",
    "crates/web",
    "crates/server",
    "crates/bench",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.99"
license = "MIT OR Apache-2.0"
repository = "https://github.com/i3months/pointblitz"
publish = false

[workspace.dependencies]
pointblitz-io = { path = "crates/io" }
pointblitz-core = { path = "crates/core" }

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
