[package]
name = "pointblitz-web"
description = "PointBlitz browser target (wasm)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pointblitz-core.workspace = true

[lints]
workspace = true
