[package]
name = "pointblitz-io"
description = "PLY stream parser and GPU-ready chunk format for PointBlitz"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]


[lints]
workspace = true

[dev-dependencies]
skyrecon-core = { git = "https://github.com/AH100-1/skyrecon", rev = "9f8a0f5ea4e740aab22062e5d40b1f131a824dae" }
